name: DynmapIRC
main: ca.celticminstrel.bukkit.DynmapIRC
version: '${project.version}'
authors:
- Celtic Minstrel
- mbaxter
depend:
- dynmap
softdepend:
- CraftIRC
- MineIRC
- MinecraftBot
- MonsterIRC